blog/urls.py
from django.urls import path,include
from blog import views

app_name='blog'

urlpatterns=[
    path('',views.blogHome,name='blogHome'),
    path('<int:pk>',views.blogPost,name='blogPost'),
    path('like', views.like_post, name="like_post"),

    
]

blog3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    path('users/',include(('users.urls','users'),namespace='users')),
    path('products/',include(('products.urls','products'),namespace='products')),
    path('videos/',include(('video.urls','video'),namespace='video')),
    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path,include
from . import views

app_name='products'
urlpatterns=[
            path('',views.category_list,name='category_list'),
            path('<slug:category_slug>/',views.product_list,name='product_list'),
]

products/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
     name=models.CharField(max_length=150,db_index=True)
     img=models.ImageField(upload_to='pics',blank=True)
     slug=models.SlugField(unique=True)
     class Meta:
        ordering=('-name',)
     def __str__(self):
        return self.name

class Products(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    name= models.CharField(max_length=150)
    desc= models.TextField()
    price=models.IntegerField()
    img=models.ImageField(upload_to='pics')
    desc1=models.TextField()
    desc2=models.TextField()
    specialOffer=models.BooleanField(default=False)
    producturl=models.URLField(max_length=40)

    class Meta:
        ordering=('-name',)
    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import get_object_or_404, render
from . models import Products,Category

# Create your views here.
def category_list(request):
    products=Products.objects.all()
    category=Category.objects.all()
    context={'products':products,'category':category}
    return render(request,'products/category_list.html',context)

def product_list(request,category_slug):
    category=Category.objects.all()
    category1=get_object_or_404(Category,slug=category_slug)
    products1=Products.objects.filter(category=category1)
    context={'category1':category1,'products1':products1,'category':category}
    return render(request,'products/product_list.html',context)

templates/products/category_list.html
{% extends 'base.html'%}
{% block productsactive %}active{% endblock productsactive %}
    {%load static%}

    {%block content%}
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2" style="padding: 2px;">
            <h6 class="text-center" style="margin: auto;font-size:20px;">Product Categories</h6>
            <hr id="hr" style="width: 16%;
            height: 2px;
            margin: 4px auto;">
            <!-- <div id="touchwarn1" style="width: 40%; margin: auto;"><p class="pt-2 text-center text-danger">Warning: Don't touch the line above</p></div> -->
             <ul>
            {%for c in category%}
              
               <li style="list-style: none; text-align:center;padding:9px 15px;background-color:#aaaaaa"><a style="text-decoration: none;color:black;padding:7px 22px;font-size:18px; text-align: center;" href="{% url 'products:product_list' c.slug %}">{{c.name}}</a></li>
            {%endfor%}
        </div>
        <div class="col-md-10">
      <!-- <section class="container-fluid customsec2 pt-3"> -->
        <h2 class="text-center" style="width: 35%; margin: auto;">Best Gaming Products</h2>
        <hr id="customhr2" style="width: 18%; height: 2px; margin:4px auto;">
        <!-- <div id="touchwarn2" style="width: 40%; margin: auto;"><p class="pt-2 text-center text-danger">Warning: Don't touch the line above</p></div> -->
        
        <div class="row py-3">
          {% for product in products %}
          <div class="col-md-4">
            <div class="card customaccessorycard" style="width: 18rem;">
              <img src="{{product.img.url}}" class="card-img-top" alt="Zebronic">
              {% if productobj.specialOffer %}
              <div class="text-center" style="position: absolute; top:7px; background-color:#1C1E29;color:aliceblue;padding:3px;">Special Offer</div>
              {% endif %}
              <div class="card-body">
                <h5 class="card-title">{{product.name}}</h5>
                <p class="card-text">{{product.desc}}</p>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">{{product.desc1}}</li>
                  <li class="list-group-item">{{product.desc2}}</li>
                  <li class="list-group-item" style="background-color: gold;">PRICE: ₹ {{product.price}}</li>
                </ul>
                <div class="card-body">
                  <a href="{{product.producturl}}" target="_blank" class="btn btn-primary btn-block accessorycardbodybtn">BUY NOW</a>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        <!-- </section> -->
      </div>
      </div>
    </div>
    {%endblock content%}

templates/products/product_list.html
{% extends 'base.html'%}
{% block productsactive %}active{% endblock productsactive %}
    {%load static%}
{%block content%}
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2">
            <h6 class="text-center" style="margin: auto;font-size:20px;">Product Categories</h6>
            <hr id="customhr1" style="width: 16%;
            height: 2px;
            margin: 4px auto;">
            <!-- <div id="touchwarn1" style="width: 40%; margin: auto;"><p class="pt-2 text-center text-danger">Warning: Don't touch the line above</p></div> -->
             <ul>
            {%for cat in category%}
              
               <li style="list-style: none; text-align:center;padding:9px 12px;background-color:#aaaaaa"><a style="text-decoration: none;color:black;padding:7px 17px;font-size:18px;" href="{% url 'products:product_list' cat.slug %}">{{cat.name}}</a></li>
            {%endfor%}
        </div>
        <div class="col-md-10">
      <!-- <section class="container-fluid customsec2 pt-3"> -->
        <h2 class="text-center" style="width: 35%; margin: auto;">{{category1.name}}</h2>
        
        <hr id="customhr2" style="width: 18%; height: 2px; margin:4px auto;">
        <!-- <div id="touchwarn2" style="width: 40%; margin: auto;"><p class="pt-2 text-center text-danger">Warning: Don't touch the line above</p></div> -->
        
        <div class="row py-3">
          {% for productobj in products1 %}
          <div class="col-md-4">
            <div class="card customaccessorycard" style="width: 18rem;">
              <img src="{{productobj.img.url}}" class="card-img-top" alt="Zebronic">
              {% if productobj.specialOffer %}
              <div class="text-center" style="position: absolute; top:7px; background-color:#1C1E29;color:aliceblue;padding:3px;">Special Offer</div>
              {% endif %}
              <div class="card-body">
                <h5 class="card-title">{{productobj.name}}</h5>
                <p class="card-text">{{productobj.desc}}</p>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">{{productobj.desc1}}</li>
                  <li class="list-group-item">{{productobj.desc2}}</li>
                  <li class="list-group-item" style="background-color: gold;">PRICE: ₹ {{productobj.price}}</li>
                </ul>
                <div class="card-body">
                  <a href="{{productobj.producturl}}" target="_blank" class="btn btn-primary btn-block accessorycardbodybtn">BUY NOW</a>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        <!-- </section> -->
      </div>
      </div>
    </div>
    {%endblock content%}