blog/urls.py
from django.urls import path,include
from blog import views

app_name='blog'

urlpatterns=[
    path('',views.blogHome,name='blogHome'),
    path('<int:pk>',views.blogPost,name='blogPost'),
    path('like', views.like_post, name="like_post"),

    
]

blog3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    path('users/',include(('users.urls','users'),namespace='users')),
    path('products/',include(('products.urls','products'),namespace='products')),
    path('videos/',include(('video.urls','video'),namespace='video')),
    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views





app_name='users'
urlpatterns=[
    path('register',views.register, name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout, name='logout'),
]

video/urls.py
from django.urls import path
from . import views

app_name='video'
urlpatterns=[
    path('postComment',views.postComment, name="postComment"),
    path('category',views.newcategory_list, name='category'),
    path('<slug:article_slug>/',views.article_detail, name='article_detail'),
    path('<slug:category_slug>',views.category_view, name='category_view'),

    #API to post a comment
    ]

video/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.timezone import now

# Create your models here.

class CategoryList(models.Model):
    name=models.CharField(max_length=150,db_index=True)
    img=models.ImageField(upload_to='categorypics',blank=True)
    slug=models.SlugField(unique=True)
    class Meta:
        ordering=('-name',)
    def __str__(self):
        return self.name
    
    
    
    
    @property
    def image_url(self):
        if self.img and hasattr(self.img, 'url'):
            return self.img.url

class Item(models.Model):
    sno=models.AutoField(primary_key=True)
    category=models.ForeignKey(CategoryList,on_delete=models.CASCADE)
    slug=models.SlugField(unique=True)
    title=models.CharField(max_length=200)
    # videourl=models.URLField(max_length=200)
    video = EmbedVideoField()  # same like models.URLField()
    modnamever=models.CharField(max_length=100,default="will be updated shortly")
    modername=models.CharField(max_length=150)
    moderyt=models.URLField(blank=True)
    moderpatreon=models.URLField(blank=True)
    modlink=models.URLField()
    fileurl=models.URLField(blank=True)
    desc=models.TextField()
    publish=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('-title',)

    def __str__(self):
        return self.title

    
class VideoComment(models.Model):
    srno = models.AutoField(primary_key=True)
    comment=models.TextField()
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    article = models.ForeignKey(Item,on_delete=models.CASCADE)
    parent=models.ForeignKey('self',on_delete=models.CASCADE,null=True)
    timestamp = models.DateTimeField(default=now)

    def __str__(self):
        return self.comment[0:10] + "..." + "by " + self.user.username

video/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import CategoryList,Item, VideoComment
from django.contrib.auth.models import User,auth
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from video.templatetags import extras



# Create your views here.
# def index(request):
#     # productarr=Products.objects.all()
#     return render(request,'blog/index.html')






def newcategory_list(request):
    # category=None
    categories=CategoryList.objects.all()
    # article=Item.objects.all()
    return render(request,'video/categorylist.html',{'categories':categories})





# def category_view(request,category_slug):
#     category=get_object_or_404(CategoryList,slug=category_slug)
#     article=Item.objects.filter(category=category)
#     context={'category':category,'article':article}
#     return render(request,'video/category_view.html',context)

def category_view(request,category_slug):
    category=CategoryList.objects.filter(slug=category_slug).first()
    article=Item.objects.filter(category=category)
    print("I am called")
    return render(request,'video/category_view.html',{'article':article,'category':category})

# def article_detail(request,article_slug):
#     article=get_object_or_404(Item,slug=article_slug)

#     context={
#         'article':article
#         }    
#     return render(request,'video/article_detail.html',context)
def article_detail(request,article_slug):
    article=Item.objects.filter(slug=article_slug).first()
    comments=VideoComment.objects.filter(article=article,parent=None)
    replies=VideoComment.objects.filter(article=article).exclude(parent=None)
    repDict={}
    for reply in replies:
        if reply.parent.srno not in repDict.keys():
            repDict[reply.parent.srno]=[reply]
        else:
            repDict[reply.parent.srno].append(reply)

    
    context={'article':article,'comments':comments,'user':request.user,'repDict':repDict}
    print("Now I am called")
    return render(request,'video/article_detail.html',context)


def postComment(request):
    if request.method=="POST":
        comment=request.POST.get("comment")
        user = request.user
        articleSno = request.POST.get("articleSno")
        article=Item.objects.get(sno=articleSno)
        parentSno=request.POST.get("parentSno")
        if parentSno=="":
            comment=VideoComment(comment=comment,user=user,article=article)
            comment.save()
            messages.success(request,"Your comment has been posted successfully")
        else:
            parent=VideoComment.objects.get(srno=parentSno)
            comment=VideoComment(comment=comment,user=user,article=article,parent=parent)

        
            comment.save()
            messages.success(request,"Your reply has been posted successfully")

    
    return HttpResponseRedirect(reverse('video:article_detail', args=(article.slug,)))

# Create your views here.

templates/video/article_detail.html
{% extends 'base.html'%}
{% block videoactive %}active{% endblock videoactive %}
{% load embed_video_tags %}
{% load humanize %}
{% load extras %}

    {%load static%}

    {%block content%}

    
    <div class="container" style="padding-left:82px;padding-right:82px">
    <div class="row">
            <div class="col-md-12 px-0 mod">
            <div class="videobox">
                 <div id="spiderheading">
                <h1> HOW TO INSTALL {{article.title}}</h1>
                </div>
                <div class="container embed-responsive embed-responsive-16by9 px-3" id="vid">
                    {%video article.video 'small'%}
                </div>
            </div>
            <hr id="customhr3" style="width:16%;height: 2px;
            margin: 10px auto;margin-top:20px;">
            <ul>
                
                <h2 style="text-align: center;">Mod Name: {{article.modnamever}}</h2>
                <p>{{article.desc|safe}}</p>
                <p> Credits: <br>
                     
                <table id="table1">
                    <tbody>
                        <tr>
                            <td>Mod Creater :</td>
                            <td>{{article.modername}}</td>
                        </tr>
                        <tr>
                            <td>{{article.modername}}'s <br>Youtube Channel</td>
                            <td><a href="{{article.moderyt}}"><button>subscribe</button></a></td>
                            
                        </tr>
                        <tr>
                            <td>{{article.modername}}'s <br>Patreon</td>
                            <td><a href="{{article.moderpatreon}}">Show Support<button></button></a></td>
                        </tr>
                    </tbody>
                </table></p>
                    <li>{{article.modername}}'s Youtube Channel: <br>
                    </li>
            </ul>
        </div>
        </div>
        
        <!-- section for comments -->
        <div class="container"> 
            <h2>{{comments.count}} Comments</h2>
            <div class="my-3">
                {% if user.is_authenticated %}
                <form action="/videos/postComment" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Write your comment</label>
                        <input type="text" class="form-control" name="comment" placeholder="Enter comment here">
                        <input type="hidden" name="parentSno" value="">
    
                    </div>
                <input type="hidden" name="articleSno" value="{{article.sno}}">
                <input type="submit" value="Submit">
                </form>
                {% else %}
                      <div class="card card-body">
                          <div class="row">
                              <div class="col-md-6">
                                <h3>Please <a href="{% url 'users:login' %}?next={% firstof request.path '/' %}">Login</a>to comment or reply</h3>
                              </div>
                              <div class="col-md-6">

                                    <h3 style="margin-top: 10px;font-weight:bold;">Don't Have Account?</h3>
                                    <button style="margin-left: 8px; padding:3px 5px;"><a href="{% url 'users:register' %}?next={% firstof request.path '/' %}" style="text-decoration: none;">Create an Account</a></button>
                            
                              </div>
                          </div>
                          
                           
                     
               
        </div>
                {% endif %}
            </div>
            
            {% for comment in comments %}
            <div class="row my-3">
                
                <div class="col-md-1"><img class="rounded mx-auto d-block" src="/static/images/user.png" alt="" style="width: 67px;"></div>
                <div class="col-md-11"><b>{{comment.user.username}}</b> &nbsp; <span class="badge badge-secondary" style="font-size: 13px;">{{comment.timestamp|naturaltime}}</span></div>
                <div>{{comment.comment}}</div>
                <div class="reply mx-0">
                    {% if user.is_authenticated %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.srno}}" aria-expanded="false" aria-controls="replyBox{{comment.srno}}">
                        Reply
                    </button>
                    <div class="collapse" id="replyBox{{comment.srno}}">
                        <div class="card card-body my-2">
                            <form action="/videos/postComment" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Post a reply</label>
                                    <input type="text" class="form-control" name="comment" placeholder="Enter comment here">
                                <input type="hidden" name="parentSno" value="{{comment.srno}}">
                
                                </div>
                            <input type="hidden" name="articleSno" value="{{article.sno}}">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                    {% else %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.srno}}" aria-expanded="false" aria-controls="replyBox{{comment.srno}}" disabled>
                       Reply
                    </button>
                    {% endif %}
                    <div class="replies my-2">
                        {% for reply in repDict|get_val:comment.srno %}
                        <div class="row">
                            <div class="col-md-1">
                                <img class="rounded mx-auto d-block" src="/static/images/user.png" alt="" style="width: 67px;"> 
                            </div>
                            <div class="col-md-11">
                                <b>{{reply.user.username}}</b> &nbsp; <span class="badge badge-secondary" style="font-size: 13px;">{{reply.timestamp|naturaltime}}</span>
                                <div>{{reply.comment}}</div>

                        </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            </div>
            {% endfor %}
        </div>
       
    {%endblock content%}

templates/video/category_view.html
{% extends 'base.html' %}
{% block videoactive %}active{% endblock videoactive %}
{%load static%}

{%block content%}
<section class="container customsec2 pt-5">
    <h2 class="text-center" style="width: 35%; margin: auto;">Mods Categories</h2>
    <hr id="customhr1" style="width: 16%;
            height: 2px;
            margin: 4px auto;">
            <div id="touchwarn1" style="width: 40%; margin: auto;"><p class="pt-2 text-center text-danger">Warning: Don't touch the line above</p></div>
                <h1>{% if category %}{{category.name}}{% else %}ALL MODS{%endif%}</h1>
                    <div class="row py-3">
                    {%for x in article%}
                    <div class="col-lg col-12 homeimg" id="img1">
                    <h5>{{x.title}}</h5>
                        <div>
                            <!-- <iframe width="360" height="215" src="" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->
                        </div>
                    <h3><a href="{% url 'video:article_detail' x.slug %}">Show me this mod installation all steps</a></h3>
                </div>
                {% endfor %}
                </div>
        </section> 
        {%endblock content%} 

templates/video/categorylist.html
{% extends 'base.html'%}
{% block videoactive %}active{% endblock videoactive %}
    {%load static%}

    {%block content%}
    <div class="container">
        <section class="container customsec2 pt-5">
            <h2 class="text-center" style="width: 35%; margin: auto;">Mods Categories</h2>
            <hr id="customhr1" style="width: 16%;
            height: 2px;
            margin: 4px auto;">
            <!-- <div id="touchwarn1" style="width: 40%; margin: auto;"><p class="pt-2 text-center text-danger">Warning: Don't touch the line above</p></div> -->
          <div class="row py-3">
            {% for c in categories %}
            <div class="col-lg col-12 homeimg" id="img1">
              
               <h5><a href="{% url 'video:category_view' c.slug %}">{{c.name}}</a></h5>
              <img class="secimg border-info" src="{{c.image_url|default_if_none:'#'}}" alt="gameplay videos">
              
            </div>
            {% endfor %}
            
        </div>
        </section>
         
    </div>
    {%endblock content%}