blog/urls.py
from django.urls import path,include
from blog import views

app_name='blog'

urlpatterns=[
    path('',views.blogHome,name='blogHome'),
    path('<int:pk>',views.blogPost,name='blogPost'),
    path('like', views.like_post, name="like_post"),

    
]

blog3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('home.urls','home'),namespace='home')),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    path('users/',include(('users.urls','users'),namespace='users')),
    path('products/',include(('products.urls','products'),namespace='products')),
    path('videos/',include(('video.urls','video'),namespace='video')),
    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include
from home import views
# from home.views import ProtectedView

app_name='home'
urlpatterns=[
    path("",views.home,name='home'),
    path("contact",views.contact,name='contact'),
    # path("contact/",ProtectedView.as_view(),name='contact'),
    path("about/",views.about,name='about'),
    path("search/",views.search,name='search'),
]

products/urls.py
from django.urls import path,include
from . import views

app_name='products'
urlpatterns=[
            path('',views.category_list,name='category_list'),
            path('<slug:category_slug>/',views.product_list,name='product_list'),
]

users/urls.py
from django.urls import path
from users import views





app_name='users'
urlpatterns=[
    path('register',views.register, name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout, name='logout'),
]

video/urls.py
from django.urls import path
from . import views

app_name='video'
urlpatterns=[
    path('postComment',views.postComment, name="postComment"),
    path('category',views.newcategory_list, name='category'),
    path('<slug:article_slug>/',views.article_detail, name='article_detail'),
    path('<slug:category_slug>',views.category_view, name='category_view'),

    #API to post a comment
    ]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% static "images" as baseUrl%}
<html lang="en">

<head>
  <title>{% block title %} {% endblock title %}</title>
  {% block mycss %} {% endblock mycss %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Goldman&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw=="
    crossorigin="anonymous" />
  <script src="{% static '/js/external.js' %}" type="text/javascript"></script>
  <link href="{% static '/css/style.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static '/css/sidenavbar.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static '/css/mod.css' %}" rel="stylesheet" type="text/css">
</head>

<body aria-hidden="false" class style>
  <nav class="navbar navbar-expand-lg shadow p-1 mb-4 bg-light rounded"
    style="font-weight: bold; background-color: #FFD700;">
    <a class="navbar-brand" style="color: grey;" href="/"><img class="nav-logo" src="{% static 'images/logo.png' %}"
        alt="blog"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon">Menu</span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% block homeactive %} {% endblock homeactive %}">
          <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item {% block videoactive %} {% endblock videoactive %}">
          <a class="nav-link" href="{% url 'video:category' %}">Videos</a>
        </li>
        <li class="nav-item {% block blogactive %} {% endblock blogactive %}">
          <a class="nav-link" href="{% url 'blog:blogHome' %}">Blog</a>
        </li>
        <li class="nav-item {% block productsactive %} {% endblock productsactive %}">
          <a class="nav-link" href="{% url 'products:category_list' %}">Gaming Accessory</a>
        </li>
        <li class="nav-item {% block contactactive %} {% endblock contactactive %}">
          <a class="nav-link" href="/contact">Contact Us</a>
        </li>
        <li class="nav-item {% block aboutactive %} {% endblock aboutactive %}">
          <a class="nav-link" href="{% url 'home:about' %}">About Us</a>
        </li>
        
      </ul>
      <form class="form-inline my-2 my-lg-0 mr-3" method="get" action="/search">

        <input class="form-control mr-sm-2" placeholder="Search this website" aria-label="Search" name="query" id="query"
          type="search">
        <button type="submit" class="btn btn-info">Search</button>
      </form>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">Hi,{{user.first_name}}</li>
        <li class="nav-item">

          <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item {% block loginactive %} {% endblock loginactive %}">
          <a class="nav-link" href="{% url 'users:login' %}">Login</a>
        </li>
        <!-- Button to trigger signup modal -->
        <li class="nav-item {% block signupactive %} {% endblock signupactive %}">
        <a class="nav-link" href="{% url 'users:register' %}">
          Sign Up
        </a>
        </li>
        
        {% endif %}
        
      </ul>
    </div>
  </nav>
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} mb-0 alert-dismissible fade show" role="alert">
    <strong>New Message: </strong>{{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
   


<!--SignUp Modal -->
<!-- <div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="signupModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="signupModalTitle">Sign Up Here</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="choose a unique username">
          </div>
          <div class="form-group">
            <label for="fname">First Name</label>
            <input type="text" class="form-control" id="fname" name="fname" placeholder="First Name">
          </div>
          <div class="form-group">
            <label for="lname">Last Name</label>
            <input type="text" class="form-control" id="lname" name="lname" placeholder="Last Name">
          </div>
          <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
          </div>
         
           <div class="form-group">
            <label for="pass1">Choose a Password</label>
            <input type="password" class="form-control" id="pass1" name="pass1" placeholder="Choose your password">
          </div>
           <div class="form-group">
            <label for="pass2">Confirm Password</label>
            <input type="password" class="form-control" id="pass2" name="pass2" placeholder="Enter your password again">
          </div>
          <button type="button" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div> -->

<!-- login modal -->
<!-- <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalTitle">Login Here</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="/users/login" method="POST">
          {% csrf_token %}
          <div class="form-group">
            {% if request.GET.next %}
                                <input type="hidden" name="next" value="{{request.GET.next}}">
                                {% endif %}
            <label for="username">Username</label>
            <input type="text" class="form-control" id="loginusername" name="username" placeholder="Enter your username">
          </div>
          
           <div class="form-group">
            <label for="pass">Password</label>
            <input type="password" class="form-control" id="pass" name="pass" placeholder="Enter your password">
          </div>
          <button type="submit" class="btn btn-primary">Login</button>
        </form>
      </div>
    </div>
  </div>
</div> -->

  {% block content%}
  {%endblock content%}



  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(event){
                      $(document).on('click', '#like', function(event){
                          event.preventDefault();
                          var pk = $(this).attr('value');
                          $.ajax({
                              type: 'POST',
                              url: '{% url "blog:like_post" %}',
                              data: {
                                  'id': pk,
                                  'csrfmiddlewaretoken': '{{ csrf_token }}'
                              },
                              datatype: 'json',
                              success: function(response){
                                  $('#like-section').html(response['form'])
      
                              },
                              error: function(rs, e){
                                  console.log(rs.responseText);
                              },
                          });
                      });
                  });
      </script>

</body>

</html>